In [57]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import Perceptron
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models

In [29]:
df = pd.read_csv("/kaggle/input/english-premier-league/final_dataset.csv",index_col=0)

In [30]:
target = []

for idx, row in df.iterrows():
    if (row["FTHG"] > row["FTAG"]):
        target.append(2)
    elif (row["FTHG"] < row["FTAG"]):
        target.append(0)
    else:
        target.append(1)

In [31]:
df = df.drop(['FTHG','FTAG','Date'], axis=1)

In [32]:
def encode_df(dataframe):
    le = LabelEncoder()
    for column in dataframe.columns:
        if dataframe[column].dtype == 'O':
            dataframe[column] = le.fit_transform(dataframe[column])
    return dataframe

#encode the dataframe
df = encode_df(df)

In [33]:
df["Result"] = target

In [34]:
df.head()

HomeTeam  AwayTeam  FTR  HTGS  ATGS  HTGC  ATGC  HTP  ATP  HM1  ...  \
0        11        24    0     0     0     0     0  0.0  0.0    2  ...   
1        12        41    0     0     0     0     0  0.0  0.0    2  ...   
2        13        27    1     0     0     0     0  0.0  0.0    2  ...   
3        15        34    1     0     0     0     0  0.0  0.0    2  ...   
4        21        16    0     0     0     0     0  0.0  0.0    2  ...   

   HTLossStreak5  ATWinStreak3  ATWinStreak5  ATLossStreak3  ATLossStreak5  \
0              0             0             0              0              0   
1              0             0             0              0              0   
2              0             0             0              0              0   
3              0             0             0              0              0   
4              0             0             0              0              0   

   HTGD  ATGD  DiffPts  DiffFormPts  Result  
0   0.0   0.0      0.0          0.0       2  
1   0.0   0.0      0.0          0.0       2  
2   0.0   0.0      0.0          0.0       0  
3   0.0   0.0      0.0          0.0       1  
4   0.0   0.0      0.0          0.0       2  

[5 rows x 37 columns]

## Logistic Regression

In [35]:
X = df.drop("Result", axis=1)
y = df["Result"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8, random_state=42)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 0.5990497076023392
Confusion Matrix:
[[ 697  426  420]
 [ 443  464  483]
 [ 224  198 2117]]
Classification Report:
              precision    recall  f1-score   support

           0       0.51      0.45      0.48      1543
           1       0.43      0.33      0.37      1390
           2       0.70      0.83      0.76      2539

    accuracy                           0.60      5472
   macro avg       0.55      0.54      0.54      5472
weighted avg       0.58      0.60      0.58      5472



/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## Decision Tree 

In [36]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 0.7496345029239766
Confusion Matrix:
[[ 796  747    0]
 [ 623  767    0]
 [   0    0 2539]]
Classification Report:
              precision    recall  f1-score   support

           0       0.56      0.52      0.54      1543
           1       0.51      0.55      0.53      1390
           2       1.00      1.00      1.00      2539

    accuracy                           0.75      5472
   macro avg       0.69      0.69      0.69      5472
weighted avg       0.75      0.75      0.75      5472



## Random Forest

In [38]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 0.7733918128654971
Confusion Matrix:
[[ 855  688    0]
 [ 552  838    0]
 [   0    0 2539]]
Classification Report:
              precision    recall  f1-score   support

           0       0.61      0.55      0.58      1543
           1       0.55      0.60      0.57      1390
           2       1.00      1.00      1.00      2539

    accuracy                           0.77      5472
   macro avg       0.72      0.72      0.72      5472
weighted avg       0.77      0.77      0.77      5472



## SVM Classifier with Linear Kernel

In [40]:
model = SVC(kernel='linear', random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 0.7764985380116959
Confusion Matrix:
[[ 872  671    0]
 [ 552  838    0]
 [   0    0 2539]]
Classification Report:
              precision    recall  f1-score   support

           0       0.61      0.57      0.59      1543
           1       0.56      0.60      0.58      1390
           2       1.00      1.00      1.00      2539

    accuracy                           0.78      5472
   macro avg       0.72      0.72      0.72      5472
weighted avg       0.78      0.78      0.78      5472



## SVM Classifier with RBF Kernel

In [41]:
model = SVC(kernel='rbf', random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 0.5020102339181286
Confusion Matrix:
[[ 369    0 1174]
 [ 166    0 1224]
 [ 161    0 2378]]
Classification Report:
              precision    recall  f1-score   support

           0       0.53      0.24      0.33      1543
           1       0.00      0.00      0.00      1390
           2       0.50      0.94      0.65      2539

    accuracy                           0.50      5472
   macro avg       0.34      0.39      0.33      5472
weighted avg       0.38      0.50      0.39      5472



/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Perceptron Classifier

In [43]:
model = Perceptron(max_iter=1000, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 0.3048245614035088
Confusion Matrix:
[[  40 1480   23]
 [  16 1326   48]
 [  16 2221  302]]
Classification Report:
              precision    recall  f1-score   support

           0       0.56      0.03      0.05      1543
           1       0.26      0.95      0.41      1390
           2       0.81      0.12      0.21      2539

    accuracy                           0.30      5472
   macro avg       0.54      0.37      0.22      5472
weighted avg       0.60      0.30      0.22      5472



## XGBoost Classifier

In [45]:
model = XGBClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 0.766264619883041
Confusion Matrix:
[[ 896  647    0]
 [ 632  758    0]
 [   0    0 2539]]
Classification Report:
              precision    recall  f1-score   support

           0       0.59      0.58      0.58      1543
           1       0.54      0.55      0.54      1390
           2       1.00      1.00      1.00      2539

    accuracy                           0.77      5472
   macro avg       0.71      0.71      0.71      5472
weighted avg       0.77      0.77      0.77      5472



## MultiLayer Perceptron Classifier

In [52]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
model = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=500, random_state=42)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 0.7538377192982456
Confusion Matrix:
[[ 893  648    2]
 [ 692  696    2]
 [   0    3 2536]]
Classification Report:
              precision    recall  f1-score   support

           0       0.56      0.58      0.57      1543
           1       0.52      0.50      0.51      1390
           2       1.00      1.00      1.00      2539

    accuracy                           0.75      5472
   macro avg       0.69      0.69      0.69      5472
weighted avg       0.75      0.75      0.75      5472



## CNN

In [63]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
y_categorical = keras.utils.to_categorical(y)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_categorical, test_size=0.2, random_state=42)
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dense(32, activation='relu'),
    layers.Dense(3, activation='softmax')
])
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)
y_pred_prob = model.predict(X_test)
y_pred = np.argmax(y_pred_prob, axis=1)
accuracy = accuracy_score(np.argmax(y_test, axis=1), y_pred)
conf_matrix = confusion_matrix(np.argmax(y_test, axis=1), y_pred)
classification_rep = classification_report(np.argmax(y_test, axis=1), y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")

Epoch 1/10
137/137 [==============================] - 1s 4ms/step - loss: 0.7978 - accuracy: 0.6351 - val_loss: 0.4843 - val_accuracy: 0.7489
Epoch 2/10
137/137 [==============================] - 0s 2ms/step - loss: 0.3985 - accuracy: 0.7836 - val_loss: 0.3764 - val_accuracy: 0.7744
Epoch 3/10
137/137 [==============================] - 0s 2ms/step - loss: 0.3586 - accuracy: 0.7926 - val_loss: 0.3658 - val_accuracy: 0.7708
Epoch 4/10
137/137 [==============================] - 0s 2ms/step - loss: 0.3494 - accuracy: 0.7946 - val_loss: 0.3644 - val_accuracy: 0.7689
Epoch 5/10
137/137 [==============================] - 0s 2ms/step - loss: 0.3423 - accuracy: 0.8019 - val_loss: 0.3634 - val_accuracy: 0.7854
Epoch 6/10
137/137 [==============================] - 0s 2ms/step - loss: 0.3395 - accuracy: 0.8081 - val_loss: 0.3631 - val_accuracy: 0.7708
Epoch 7/10
137/137 [==============================] - 0s 2ms/step - loss: 0.3337 - accuracy: 0.8159 - val_loss: 0.3660 - val_accuracy: 0.7781
Epoch 

## LSTM

In [64]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
y_categorical = keras.utils.to_categorical(y)
X_reshaped = X_scaled.reshape((X_scaled.shape[0], 1, X_scaled.shape[1]))
X_train, X_test, y_train, y_test = train_test_split(X_reshaped, y_categorical, test_size=0.2, random_state=42)
model = keras.Sequential([
    layers.LSTM(50, activation='relu', input_shape=(X_train.shape[1], X_train.shape[2])),
    layers.Dense(3, activation='softmax')
])
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)
y_pred_prob = model.predict(X_test)
y_pred = np.argmax(y_pred_prob, axis=1)
accuracy = accuracy_score(np.argmax(y_test, axis=1), y_pred)
conf_matrix = confusion_matrix(np.argmax(y_test, axis=1), y_pred)
classification_rep = classification_report(np.argmax(y_test, axis=1), y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")

Epoch 1/10
137/137 [==============================] - 2s 5ms/step - loss: 0.9728 - accuracy: 0.5289 - val_loss: 0.8267 - val_accuracy: 0.6758
Epoch 2/10
137/137 [==============================] - 0s 3ms/step - loss: 0.6516 - accuracy: 0.7409 - val_loss: 0.5047 - val_accuracy: 0.7726
Epoch 3/10
137/137 [==============================] - 0s 3ms/step - loss: 0.4251 - accuracy: 0.7882 - val_loss: 0.3933 - val_accuracy: 0.7872
Epoch 4/10
137/137 [==============================] - 0s 3ms/step - loss: 0.3715 - accuracy: 0.7910 - val_loss: 0.3689 - val_accuracy: 0.7909
Epoch 5/10
137/137 [==============================] - 0s 3ms/step - loss: 0.3586 - accuracy: 0.7935 - val_loss: 0.3619 - val_accuracy: 0.7900
Epoch 6/10
137/137 [==============================] - 0s 3ms/step - loss: 0.3511 - accuracy: 0.7937 - val_loss: 0.3636 - val_accuracy: 0.7744
Epoch 7/10
137/137 [==============================] - 0s 3ms/step - loss: 0.3476 - accuracy: 0.8019 - val_loss: 0.3592 - val_accuracy: 0.7936
Epoch 

## RNN

In [65]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
y_categorical = keras.utils.to_categorical(y)
X_reshaped = X_scaled.reshape((X_scaled.shape[0], 1, X_scaled.shape[1]))
X_train, X_test, y_train, y_test = train_test_split(X_reshaped, y_categorical, test_size=0.2, random_state=42)
model = keras.Sequential([
    layers.SimpleRNN(50, activation='relu', input_shape=(X_train.shape[1], X_train.shape[2])),
    layers.Dense(3, activation='softmax')
])
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)
y_pred_prob = model.predict(X_test)
y_pred = np.argmax(y_pred_prob, axis=1)
accuracy = accuracy_score(np.argmax(y_test, axis=1), y_pred)
conf_matrix = confusion_matrix(np.argmax(y_test, axis=1), y_pred)
classification_rep = classification_report(np.argmax(y_test, axis=1), y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")

Epoch 1/10
137/137 [==============================] - 2s 5ms/step - loss: 0.8508 - accuracy: 0.6194 - val_loss: 0.6383 - val_accuracy: 0.7342
Epoch 2/10
137/137 [==============================] - 0s 3ms/step - loss: 0.5174 - accuracy: 0.7727 - val_loss: 0.4515 - val_accuracy: 0.7726
Epoch 3/10
137/137 [==============================] - 0s 3ms/step - loss: 0.4090 - accuracy: 0.7914 - val_loss: 0.3981 - val_accuracy: 0.7790
Epoch 4/10
137/137 [==============================] - 0s 3ms/step - loss: 0.3748 - accuracy: 0.7916 - val_loss: 0.3782 - val_accuracy: 0.7945
Epoch 5/10
137/137 [==============================] - 0s 2ms/step - loss: 0.3595 - accuracy: 0.7932 - val_loss: 0.3764 - val_accuracy: 0.7689
Epoch 6/10
137/137 [==============================] - 0s 3ms/step - loss: 0.3531 - accuracy: 0.7955 - val_loss: 0.3686 - val_accuracy: 0.7872
Epoch 7/10
137/137 [==============================] - 0s 2ms/step - loss: 0.3472 - accuracy: 0.8037 - val_loss: 0.3708 - val_accuracy: 0.7717
Epoch 

# Score Report
```
                    Precision  Recall   F1 Score
Logistic Regression   0.58      0.60      0.58
Decision Trees        0.75      0.75      0.75
Random Forest         0.77      0.77      0.77
SVM Classifier Linear 0.78      0.78      0.78
SVM Classifier RBF    0.38      0.50      0.39
Perceptron Classifier 0.60      0.30      0.22
XGBoost Classifier    0.77      0.77      0.77
Multilayer Perceptron 0.75      0.75      0.75
CNN                   0.76      0.77      0.76
LSTM                  0.77      0.77      0.77
RNN                   0.78      0.78      0.77
```